import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import {
  type NatsService,
  natsWiringDriftFailures,
  natsWiringFailures,
  ONE_LOCATION_DOCS,
  oneLocationFailures,
  trackedCounts,
} from './census'

/**
 * The drift-failure test for the one-location invariant (T25 / ADR-0038, census check b4). The gate's
 * whole claim is: a tracked count (ADRs, services, packages, boundaries, falsifiable claims) has ONE
 * editable home, and a DEFINITE restatement elsewhere that disagrees is RED. These tests are its teeth:
 * edit a derived value out of band → the gate reds; in-band → green; hedged/­block-gated → skipped.
 *
 * `oneLocationFailures` is the pure core (no fs), driven here with fixtures so the falsifier is
 * deterministic and offline. The repo-clean test reads the real front-door docs and asserts zero
 * drift, so a future hand-edit that desyncs a tracked count fails this unit AND `pnpm census`.
 */

const ROOT = process.cwd()

describe('one-location invariant (census b4)', () => {
  it('passes on the real front-door docs: every tracked count agrees with its derived source', () => {
    const docs = ONE_LOCATION_DOCS.map((path) => ({
      path,
      text: readFileSync(resolve(ROOT, path), 'utf8'),
    }))
    expect(oneLocationFailures(docs, trackedCounts())).toEqual([])
  })

  it('reds when a derived value is edited out of band (a hand-typed ADR total that disagrees)', () => {
    const wrong = trackedCounts().ADR + 1
    const docs = [
      { path: 'FIXTURE.md', text: `The architecture decisions: all ${wrong} ADRs, listed.` },
    ]
    const failures = oneLocationFailures(docs, trackedCounts())
    expect(failures).toHaveLength(1)
    expect(failures[0]).toContain('ONE-LOCATION: FIXTURE.md')
  })

  it('reds a drifted boundary count and names the derived value to align to', () => {
    const docs = [{ path: 'FIXTURE.md', text: 'The honeycomb spans 999 boundaries in total.' }]
    const failures = oneLocationFailures(docs, trackedCounts())
    expect(failures[0]).toContain(`the derived boundary count is ${trackedCounts().boundary}`)
  })

  it('stays green on an in-band restatement (the count matches the derived source)', () => {
    const right = trackedCounts().boundary
    const docs = [{ path: 'FIXTURE.md', text: `The honeycomb spans all ${right} boundaries.` }]
    expect(oneLocationFailures(docs, trackedCounts())).toEqual([])
  })

  it('skips a HEDGED approximation (~ / about / over) — prose, not a second editable home', () => {
    const wrong = trackedCounts().boundary + 50
    const docs = [
      { path: 'FIXTURE.md', text: `roughly ${wrong} boundaries, give or take, and ~${wrong} ADRs` },
    ]
    expect(oneLocationFailures(docs, trackedCounts())).toEqual([])
  })

  it('skips lines inside a byte-gated render block (the stats block is the count’s one home)', () => {
    const wrong = trackedCounts().ADR + 7
    const text = [
      '<!-- stats:start (generated by `pnpm stats:render --readme`; do not edit) -->',
      `9 services · 7 packages · ${wrong} ADRs · 13 boundaries · 23 falsifiable claims`,
      '<!-- stats:end -->',
    ].join('\n')
    expect(oneLocationFailures([{ path: 'FIXTURE.md', text }], trackedCounts())).toEqual([])
  })

  it('ignores a non-tracked count (a subset "4 claims" or a milestone count is legitimate prose)', () => {
    const docs = [{ path: 'FIXTURE.md', text: '4 claims demo the mechanic across 12 milestones.' }]
    expect(oneLocationFailures(docs, trackedCounts())).toEqual([])
  })
})

/**
 * The drift-failure test for the NATS-wiring invariant (census check b5). The gate's claim: a service
 * whose src connects to NATS must declare NATS_URL in its deploy values, or it CrashLoopBackOffs
 * in-cluster (the Milestone-13 identity bug). `natsWiringFailures` is the pure core, driven with
 * fixtures; the repo-clean test runs the real fs probe so a future hand-edit that drops NATS_URL from
 * a connectNats service fails this unit AND `pnpm census`.
 */
describe('NATS wiring invariant (census b5)', () => {
  it('passes on the real tree: every connectNats service declares NATS_URL', () => {
    expect(natsWiringDriftFailures()).toEqual([])
  })

  it('reds the identity-shaped case: connects to NATS, deployed, but no NATS_URL', () => {
    const services: NatsService[] = [
      { name: 'identity', callsNats: true, valuesExists: true, valuesHasNatsUrl: false },
    ]
    const failures = natsWiringFailures(services)
    expect(failures).toHaveLength(1)
    expect(failures[0]).toContain('NATS WIRING: services/identity')
    expect(failures[0]).toContain('NATS_URL')
  })

  it('stays green when a connectNats service declares NATS_URL', () => {
    const services: NatsService[] = [
      { name: 'content', callsNats: true, valuesExists: true, valuesHasNatsUrl: true },
    ]
    expect(natsWiringFailures(services)).toEqual([])
  })

  it('does not flag a service that never connects to NATS (the web frontend has no broker)', () => {
    const services: NatsService[] = [
      { name: 'web', callsNats: false, valuesExists: true, valuesHasNatsUrl: false },
    ]
    expect(natsWiringFailures(services)).toEqual([])
  })

  it('does not flag a connectNats service that is not cluster-deployed (no values.yaml = out of scope)', () => {
    const services: NatsService[] = [
      { name: 'some-tool', callsNats: true, valuesExists: false, valuesHasNatsUrl: false },
    ]
    expect(natsWiringFailures(services)).toEqual([])
  })
})
