import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { ALERT_ENDPOINTS, CONSUMER_LAG_SLO, SLO_TARGETS } from '@qaroom/contracts'
import { CONSUMER_LAG_METRIC } from '@qaroom/otel/consumer-lag-metrics'

/**
 * Project the in-code SLOs into Prometheus alerting rules (ADR-0034) — the SAME one-source pattern as
 * `scripts/k6-gen-thresholds.ts`: SLO_TARGETS + CONSUMER_LAG_SLO are the single source, and every
 * alert threshold is DERIVED here, never hand-typed in YAML, so the alert and the documented SLO can
 * never drift. `scripts/gen-alert-rules.test.ts` regenerates-and-diffs this file in the always-on
 * `pnpm test:scripts` lane; `deploy/observability/alerts.test.yaml` exercises each rule with promtool.
 *
 *   pnpm alerts:gen   write deploy/observability/alerts.gen.yaml
 */

const ROOT = process.cwd()
const outPath = resolve(ROOT, 'deploy/observability/alerts.gen.yaml')

/** The OTel HTTP server duration histogram (seconds), as the Collector exposes it to Prometheus. */
const HTTP_HISTOGRAM = 'http_server_request_duration_seconds'

const cap = (s: string): string => s.charAt(0).toUpperCase() + s.slice(1)
/** Drop the leading `METHOD ` from an SLO route, leaving the `http.route` label value. */
const pathOf = (route: string): string => route.split(' ')[1] ?? route

interface Rule {
  readonly alert: string
  readonly expr: string
  readonly forDuration: string
  readonly slo: string
  readonly summary: string
}

function httpRules(): Rule[] {
  return ALERT_ENDPOINTS.flatMap((key) => {
    const target = SLO_TARGETS[key]
    const route = pathOf(target.route)
    const p95Seconds = (target.latencyMs?.p95 ?? 0) / 1000
    return [
      {
        alert: `HighErrorRate${cap(key)}`,
        expr:
          `sum(rate(${HTTP_HISTOGRAM}_count{http_route="${route}",http_response_status_code=~"5.."}[5m]))` +
          ` / sum(rate(${HTTP_HISTOGRAM}_count{http_route="${route}"}[5m])) > ${target.errorRate}`,
        forDuration: '5m',
        slo: key,
        summary: `${key} error rate over its SLO (${target.errorRate})`,
      },
      {
        alert: `HighLatencyP95${cap(key)}`,
        expr:
          `histogram_quantile(0.95, sum by (le) (rate(${HTTP_HISTOGRAM}_bucket{http_route="${route}"}[5m])))` +
          ` > ${p95Seconds}`,
        forDuration: '5m',
        slo: key,
        summary: `${key} p95 latency over its SLO (${p95Seconds}s)`,
      },
    ]
  })
}

function asyncRules(): Rule[] {
  const maxAckAgeSeconds = CONSUMER_LAG_SLO.maxAckAgeMs / 1000
  return [
    {
      alert: 'ConsumerLagPendingHigh',
      expr: `${CONSUMER_LAG_METRIC.numPending} > ${CONSUMER_LAG_SLO.maxPending}`,
      forDuration: '1m',
      slo: 'consumer-lag',
      summary: `durable {{ $labels.durable }} num_pending over the CONSUMER_LAG_SLO maxPending (${CONSUMER_LAG_SLO.maxPending})`,
    },
    {
      alert: 'ConsumerLagAckAgeHigh',
      expr: `${CONSUMER_LAG_METRIC.oldestUnackedAgeSeconds} > ${maxAckAgeSeconds}`,
      forDuration: '1m',
      slo: 'consumer-lag',
      summary: `durable {{ $labels.durable }} oldest-unacked age over the CONSUMER_LAG_SLO maxAckAgeMs (${maxAckAgeSeconds}s)`,
    },
  ]
}

function renderGroup(name: string, rules: Rule[]): string[] {
  return [
    `  - name: ${name}`,
    '    rules:',
    ...rules.flatMap((r) => [
      `      - alert: ${r.alert}`,
      `        expr: '${r.expr}'`,
      `        for: ${r.forDuration}`,
      '        labels:',
      '          severity: warning',
      `          slo: ${r.slo}`,
      '        annotations:',
      `          summary: '${r.summary}'`,
      "          runbook: 'docs/slos.md'",
    ]),
  ]
}

export function renderAlertRules(): string {
  const lines = [
    '# Generated by `pnpm alerts:gen` from packages/contracts/src/slos.ts — do not edit by hand.',
    '# Every threshold derives from SLO_TARGETS + CONSUMER_LAG_SLO (the single source); `pnpm test:scripts`',
    '# fails the build if this drifts. promtool tests: deploy/observability/alerts.test.yaml.',
    'groups:',
    ...renderGroup('qaroom-http-slo', httpRules()),
    ...renderGroup('qaroom-async-slo', asyncRules()),
  ]
  return `${lines.join('\n')}\n`
}

function main(): void {
  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, renderAlertRules())
  process.stdout.write(`wrote ${outPath}\n`)
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main()
}
