import { pathToFileURL } from 'node:url'
import { BOUNDARY_REGISTRY } from './lib/manifests/boundary-registry'

/**
 * Render the breadth table from the boundary registry (the 2026-06-11 critique's consistency fix:
 * three hand-maintained boundary tables had drifted; now one source renders the table that lives in
 * docs/02-architecture.md and `pnpm claims:verify` byte-gates it).
 *
 *   pnpm boundaries:render   print the block (for injection into docs/02 + the gate)
 */

export const BOUNDARIES_START =
  '<!-- boundaries:start (generated by `pnpm boundaries:render`; do not edit) -->'
export const BOUNDARIES_END = '<!-- boundaries:end -->'

export function renderBoundariesBlock(): string {
  const rows = BOUNDARY_REGISTRY.map(
    (b) => `| ${b.label} | ${b.breaks} | ${b.leadTechnique} |`,
  ).join('\n')
  return `${BOUNDARIES_START}
| Boundary | What can break | Lead technique |
|---|---|---|
${rows}
${BOUNDARIES_END}`
}

function main(): void {
  process.stdout.write(`${renderBoundariesBlock()}\n`)
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main()
}
