import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { BOUNDARIES, CLAIMS } from '@qaroom/contracts/claims'
import { TestResultsSummary } from '@qaroom/contracts/test-results-schema'

/**
 * Render the QARoom "stats" projection: a single drift-gated README/llms.txt line whose every number
 * is DERIVED from a machine-readable source, never hand-typed. The root fix for the stale-front-door
 * weak axis (README said "ten milestones / 214 tests / 3 services / 11 ADRs" while reality is 13
 * milestones / 8 services / 20 ADRs). Mirrors scripts/render-claims.ts: a side-effect-free renderer +
 * markers, byte-gated by scripts/claims-verify.ts. Excludes summary.json's volatile generated_at /
 * commit so the block stays byte-stable until a COUNT actually changes (then re-run + commit).
 *
 *   pnpm stats:render            print the block
 *   pnpm stats:render --readme   same (for injection + the gate)
 */

const ROOT = process.cwd()

/** Count immediate child dirs that contain a package.json (a real workspace member). */
function countWorkspace(dir: string): { count: number; names: string[] } {
  const root = resolve(ROOT, dir)
  if (!existsSync(root)) return { count: 0, names: [] }
  const names = readdirSync(root, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(resolve(root, e.name, 'package.json')))
    .map((e) => e.name)
    .sort()
  return { count: names.length, names }
}

function adrCount(): number {
  const dir = resolve(ROOT, 'docs/adr')
  if (!existsSync(dir)) return 0
  return readdirSync(dir).filter((f) => /^\d{4}-.*\.md$/.test(f)).length
}

function testTotals(): string {
  const path = resolve(ROOT, 'test-results/summary.json')
  if (!existsSync(path)) return 'tests not yet run'
  const s = TestResultsSummary.parse(JSON.parse(readFileSync(path, 'utf8')))
  return `${s.totals.passed} passed / ${s.totals.failed} failed / ${s.totals.skipped} skipped across ${s.runners.length} runners`
}

export const STATS_START =
  '<!-- stats:start (generated by `pnpm stats:render --readme`; do not edit) -->'
export const STATS_END = '<!-- stats:end -->'

export function renderStatsBlock(): string {
  const services = countWorkspace('services')
  const packages = countWorkspace('packages')
  const helm = existsSync(resolve(ROOT, 'packages/helm-template')) ? ' + 1 helm chart' : ''
  // The named boundaries (the manifest BOUNDARIES enum minus its "meta" lane).
  const boundaries = BOUNDARIES.filter((b) => b !== 'meta').length
  return `${STATS_START}
${services.count} services · ${packages.count} packages${helm} · ${adrCount()} ADRs · ${boundaries} boundaries · ${CLAIMS.length} falsifiable claims · ${testTotals()}

<sub>These numbers are read from the source (the test results, the manifest, the folders on disk), not typed by hand. \`pnpm stats:render\` writes this line and \`pnpm claims:verify\` fails the build if it goes stale.</sub>
${STATS_END}`
}

function main(): void {
  process.stdout.write(`${renderStatsBlock()}\n`)
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main()
}
