import { existsSync, readdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { BOUNDARY_REGISTRY } from './lib/manifests/boundary-registry'
import { CLAIMS } from './lib/manifests/claims'

/**
 * Render the QARoom "stats" projection: a single drift-gated line (lives in ARCHITECTURE.md §1) whose
 * every number is DERIVED from a machine-readable source, never hand-typed. The root fix for the
 * stale-front-door weak axis (the front door once said "ten milestones / 214 tests / 3 services /
 * 11 ADRs" while reality is 12 milestones / 9 services / 23 ADRs). Mirrors scripts/render-claims.ts:
 * a side-effect-free renderer + markers, byte-gated by scripts/claims-verify.ts. Excludes summary.json's
 * volatile generated_at / commit so the block stays byte-stable until a COUNT actually changes
 * (then re-run + commit).
 *
 *   pnpm stats:render            print the block
 *   pnpm stats:render --readme   same (for injection into ARCHITECTURE.md + the gate)
 */

const ROOT = process.cwd()

/** Count immediate child dirs that contain a package.json (a real workspace member). Exported so the
 * one-location drift gate (scripts/census.ts) derives the service/package count from the SAME source
 * as this stats block — the two projections cannot disagree on how a count is computed. */
export function countWorkspace(dir: string): { count: number; names: string[] } {
  const root = resolve(ROOT, dir)
  if (!existsSync(root)) return { count: 0, names: [] }
  const names = readdirSync(root, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(resolve(root, e.name, 'package.json')))
    .map((e) => e.name)
    .sort()
  return { count: names.length, names }
}

/** Count committed ADRs (`docs/adr/NNNN-*.md`). Exported for the one-location drift gate. */
export function adrCount(): number {
  const dir = resolve(ROOT, 'docs/adr')
  if (!existsSync(dir)) return 0
  return readdirSync(dir).filter((f) => /^\d{4}-.*\.md$/.test(f)).length
}

export const STATS_START =
  '<!-- stats:start (generated by `pnpm stats:render --readme`; do not edit) -->'
export const STATS_END = '<!-- stats:end -->'

export function renderStatsBlock(): string {
  const services = countWorkspace('services')
  const packages = countWorkspace('packages')
  const helm = existsSync(resolve(ROOT, 'packages/helm-template')) ? ' + 1 helm chart' : ''
  // The documented boundaries (the registry that renders the docs/02 breadth table), so the stats
  // line and the table can never disagree on the count.
  const boundaries = BOUNDARY_REGISTRY.length
  // Deliberately NO live test-totals here. The pass/fail/skip count is environment-dependent (key
  // present? pgvector present? gauntlet folds present?), so byte-gating it makes claims:verify flaky
  // across CI vs local vs gauntlet. The front-door block carries only STABLE architecture-shape
  // counts (folders + manifest); the live test numbers live in test-results/summary.json + the
  // gauntlet report, where their provenance is explicit. (Removed 2026-06-10 when wiring claims:verify
  // into CI surfaced the volatility — a committed "30 failed" from a gauntlet run that a keyless CI
  // run never reproduces.)
  return `${STATS_START}
${services.count} services · ${packages.count} packages${helm} · ${adrCount()} ADRs · ${boundaries} boundaries · ${CLAIMS.length} falsifiable claims

<sub>These counts are read from the source (the manifest + the folders on disk), not typed by hand. \`pnpm stats:render\` writes this line and \`pnpm claims:verify\` fails the build if it drifts. Live test totals come from a CI run's \`test-results/summary.json\` artifact (gitignored here); \`pnpm prove\` reads them locally.</sub>
${STATS_END}`
}

function main(): void {
  process.stdout.write(`${renderStatsBlock()}\n`)
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main()
}
