import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { adrFiles } from './render-stats'

/**
 * Render docs/adr/README.md: a one-line-per-ADR index (number · status · decision) so a reader
 * arriving from the root README's "decisions" link meets a scannable table, not a wall of 39
 * long filenames with no visible status. DERIVED from the files, never typed by hand, the same
 * discipline as render-stats.ts: re-run when an ADR lands or changes status, commit the result.
 *
 *   pnpm adr:index            write docs/adr/README.md
 *   pnpm adr:index --check     fail (non-zero) if the committed file has drifted
 */

const ROOT = process.cwd()
const ADR_DIR = resolve(ROOT, 'docs/adr')
const OUT = resolve(ADR_DIR, 'README.md')

type Adr = { num: string; status: string; title: string; file: string }

/** The decision in one line: the `# ` heading with the redundant "ADR NNNN: " / "ADR-0001 — " prefix stripped. */
function decisionLine(heading: string): string {
  return heading.replace(/^ADR[\s-]*\d{4}\s*[:—-]\s*/i, '').trim()
}

export function readAdrs(): Adr[] {
  return adrFiles().map((file) => {
    const src = readFileSync(resolve(ADR_DIR, file), 'utf8')
    const num = file.slice(0, 4)
    const heading = src.match(/^# (.+)$/m)?.[1] ?? file
    // Tolerate both `- **Status:**` and `**Status:**`; keep only the glanceable head
    // (everything before the first `(`, `,`, `—`, or `.`) — the nuance lives in the file.
    const rawStatus = src.match(/^-? *\*\*Status:\*\*\s*(.+)$/m)?.[1]?.trim() ?? '—'
    const status = (rawStatus.split(/[(,—.]/)[0] ?? rawStatus).trim()
    return { num, status, title: decisionLine(heading), file }
  })
}

export function renderAdrIndex(adrs: Adr[]): string {
  // Honor the house style (no em-dashes in the rendered docs): source ADR titles use them, so
  // normalize to a comma in this projection. The ADR files themselves are unchanged.
  const clean = (s: string): string => s.replace(/\s*—\s*/g, ', ')
  const rows = adrs
    .map((a) => `| [${a.num}](${a.file}) | ${clean(a.status)} | ${clean(a.title)} |`)
    .join('\n')
  return `<!-- generated by \`pnpm adr:index\`; do not edit by hand -->
# Architecture Decision Records

Every significant decision, paired with the alternatives it rejected. [ADR-0001](0001-foundational-decisions.md)
is the immutable foundation; everything else is dated and superseding. \`Proposed\` rows are the active
planning frontier, not stale drafts.

This index is generated from the files (\`pnpm adr:index\`), so the table can't drift from what's on disk.

| # | Status | Decision |
|---|---|---|
${rows}
`
}

function main(): void {
  const rendered = renderAdrIndex(readAdrs())
  if (process.argv.includes('--check')) {
    const current = readFileSync(OUT, 'utf8')
    if (current !== rendered) {
      process.stderr.write('adr:index drift: run `pnpm adr:index` and commit docs/adr/README.md\n')
      process.exit(1)
    }
    process.stdout.write('adr:index ✓: docs/adr/README.md matches the ADR files\n')
    return
  }
  writeFileSync(OUT, rendered)
  process.stdout.write(`adr:index: wrote ${OUT} (${readAdrs().length} ADRs)\n`)
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main()
}
