import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { BOUNDARY_REGISTRY } from './lib/manifests/boundary-registry'
import { CLAIMS } from './lib/manifests/claims'
import { loadSummary, resolveEvidence } from './lib/claim-evidence'

/**
 * Render the falsifiable-claim manifest into its reader projections: docs/claims.md (verdicts,
 * GitHub-renderable) and the stable block that lives in ARCHITECTURE.md §4. All DERIVED from the one
 * manifest joined to the frozen summary.json: live numbers are read, never hand-typed, and an
 * absent/stale runner renders STALE (honest), never a faked green. The stable block carries NO live
 * numbers so it stays byte-comparable (claims:verify drift-gates it).
 *
 *   pnpm claims:render            write docs/claims.md
 *   pnpm claims:render --readme   print the stable block to stdout (for injection into ARCHITECTURE.md + the gate)
 */

const ROOT = process.cwd()

function verdict(): { line: string; verified: number; stale: number } {
  const summary = loadSummary()
  let verified = 0
  let stale = 0
  for (const claim of CLAIMS) {
    if (resolveEvidence(claim, summary).stale) stale++
    else verified++
  }
  const boundaries = new Set(CLAIMS.map((c) => c.registryRow)).size
  const staleNote = stale > 0 ? ` (${stale} stale until summary.json is regenerated in CI)` : ''
  return {
    line: `${CLAIMS.length} falsifiable claims across ${boundaries} of the ${BOUNDARY_REGISTRY.length} documented boundaries. ${verified} verified${staleNote}`,
    verified,
    stale,
  }
}

// The GitHub-renderable verdict surface (the 2026-06-11 critique: the README's "live verdicts"
// link must land somewhere that renders).
function renderClaimsMarkdown(): string {
  const summary = loadSummary()
  const v = verdict()
  const rows = CLAIMS.map((claim) => {
    const ev = resolveEvidence(claim, summary)
    const status = ev.stale ? 'STALE' : 'VERIFIED'
    // Suite-level, and labelled as such: the runner's pass count proves the gate's suite is green,
    // not that N assertions belong to this one claim (the 2026-06-11 critique read an unlabelled
    // "passed=190" twice and rightly called it opaque).
    const evText =
      ev.value === null
        ? 'unresolved'
        : `runner \`${claim.evidence.runner}\`: ${claim.evidence.field}=${ev.value} (suite-level)`
    return `| ${status} | ${claim.claim} | \`${claim.registryRow}\` | \`${claim.toggle}\` | ${evText} | \`pnpm prove ${claim.id} --break\` |`
  }).join('\n')
  const foot = summary
    ? `summary.json, commit ${summary.commit?.slice(0, 7) ?? 'unknown'}, generated ${summary.generated_at}`
    : 'no test-results/summary.json'
  return `# Falsifiable claims, with live verdicts

> Generated by \`pnpm claims:render\`; do not edit by hand. ${v.line}.

A VERIFIED claim resolved against the evidence below; a STALE claim's runner is absent from the
current snapshot and resolves on the next full run. A claim that cannot go red when its toggle is
set fails \`pnpm claims:verify\` outright: that is the gate, not this page.

| Status | Claim | Boundary | Breaks when | Evidence | Falsify |
|---|---|---|---|---|---|
${rows}

Derived from ${foot}. An unresolved claim renders STALE, never a faked green.
`
}

// Stable block (lives in ARCHITECTURE.md §4), manifest projection only (NO live numbers), so it is
// byte-comparable and drift-gated by claims:verify. Live numbers live in docs/claims.md. The
// README_* names are kept as identifiers for compatibility; the marker string is `claims:*`.
export const README_START =
  '<!-- claims:start (generated by `pnpm claims:render --readme`; do not edit) -->'
export const README_END = '<!-- claims:end -->'
export function renderReadmeBlock(): string {
  const rows = CLAIMS.map((c) => `| ${c.claim} | \`${c.registryRow}\` | \`${c.id}\` |`).join('\n')
  return `${README_START}
## Falsifiable claims

> Don't trust the green check. Flip the switch. Every claim comes with the bug that breaks it and the test that catches that bug. You run one command, a real test turns red. The status is read from the test run, not typed by hand. Full list and the matrix: \`pnpm prove\`; live verdicts: [docs/claims.md](docs/claims.md).

Falsify any row: \`pnpm prove <id> --break\`. The toggle each claim breaks under is in [docs/claims.md](docs/claims.md).

| Claim | Boundary | Id |
|---|---|---|
${rows}
${README_END}`
}

function main(): void {
  if (process.argv.includes('--readme')) {
    process.stdout.write(`${renderReadmeBlock()}\n`)
    return
  }
  writeFileSync(resolve(ROOT, 'docs/claims.md'), renderClaimsMarkdown())
  process.stdout.write(`wrote docs/claims.md (${CLAIMS.length} claims)\n`)
}

// Run only when invoked directly; importing for renderReadmeBlock (claims-verify) must be side-effect-free.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main()
}
