import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { TOGGLES } from './lib/manifests/detection-matrix'
import { DetectionMatrixArtifact, type MatrixCell } from './lib/manifests/detection-matrix-schema'
import { renderMatrixSvg, type SvgTier } from './lib/matrix-svg'

/**
 * Render the detection-matrix projections from test-results/detection-matrix.json: the committed
 * human-readable doc (including the heat-grid kicker + SVG and the three curated rows, folded in
 * from the old README front-door blocks) and the SVGs themselves. Derived-only (render-claims
 * discipline): every cell, count, and pixel comes from the artifact; nothing is hand-typed.
 *
 *   pnpm matrix:render           # write docs/detection-matrix.md + docs/assets/*.svg + evidence snapshot
 *   pnpm matrix:render --check   # drift gate: committed files must equal a fresh render
 *
 * Freshness is deliberately NOT CI-gated — cluster and llm tiers cannot run per-PR, and the
 * artifact is gitignored, so this gate runs where the artifact exists (locally, the gauntlet).
 * Staleness stays visible per-cell (commit + date).
 */
const ROOT = process.cwd()
const artifactPath = resolve(ROOT, 'test-results/detection-matrix.json')
const docPath = resolve(ROOT, 'docs/detection-matrix.md')
const assetsDir = resolve(ROOT, 'docs/assets')
const svgLightPath = resolve(assetsDir, 'detection-matrix-light.svg')
const svgDarkPath = resolve(assetsDir, 'detection-matrix-dark.svg')

if (!existsSync(artifactPath)) {
  process.stderr.write('no test-results/detection-matrix.json — run pnpm matrix first\n')
  process.exit(2)
}
const artifact = DetectionMatrixArtifact.parse(JSON.parse(readFileSync(artifactPath, 'utf8')))

const TS_COLUMNS = [
  'unit',
  'integration',
  'property',
  'mbt',
  'pact',
  'pact-oas-crosscheck',
  'reverse-conformance',
]
const PY_COLUMNS = ['py-unit', 'py-conformance', 'metamorphic']
const LIVE_COLUMNS = [
  'smoke',
  'k6',
  'mbt-live',
  'schemathesis',
  'tracetest',
  'tenant-spans',
  'chaos',
]
const LLM_COLUMNS = ['deepeval', 'redteam']

// Cell marks are screen-reader-pronounceable: VoiceOver/NVDA announce ✓/✗/$ cleanly but skip
// or mangle the middle dot and em dash, which made "no code path" vs "not run yet" (the matrix's
// central distinction) sound identical. Hence n/a + n/r.
const MARK: Record<MatrixCell['status'], string> = {
  caught: '✓',
  missed: '✗',
  na: 'n/a',
  'skipped-cost': '$',
  unstable: '~',
}

// Abbreviated column headers keep Tier A near ~100ch rendered instead of ~140ch (one mobile
// scroll instead of three); the legend maps them back.
const COL_LABEL: Record<string, string> = {
  'pact-oas-crosscheck': 'pact-oas',
  'reverse-conformance': 'rev-conf',
  'py-conformance': 'py-conf',
}
const label = (col: string) => COL_LABEL[col] ?? col

const cellFor = (toggleId: string, technique: string, tier: MatrixCell['tier']) =>
  artifact.cells.find((c) => c.toggle === toggleId && c.technique === technique && c.tier === tier)

function row(toggleId: string, isPy: boolean, columns: string[], tier: MatrixCell['tier']): string {
  return columns
    .map((col) => {
      const crossRuntime =
        (isPy && tier === 'in-proc' && TS_COLUMNS.includes(col)) ||
        (!isPy && tier === 'in-proc' && PY_COLUMNS.includes(col))
      if (crossRuntime) return 'n/a'
      const cell = cellFor(toggleId, col, tier)
      return cell ? MARK[cell.status] : 'n/r'
    })
    .join(' | ')
}

function renderDoc(): string {
  const md: string[] = []
  md.push('# The detection matrix')
  md.push('')
  md.push(
    '> Generated by `pnpm matrix:render` from `test-results/detection-matrix.json`; do not edit by hand (`pnpm matrix:verify` gates drift).',
  )
  md.push('')
  md.push(
    'Every deliberate-bug toggle in the repo, armed one at a time, against the whole battery. Tier A runs in-process (Vitest and pytest, no cluster); Tier B runs against the live k3d cluster; Tier C runs against the real model, with cost recorded. Row ids are matrix slugs; each maps to one env toggle (shown in the per-toggle detail below).',
  )
  md.push('')
  md.push('| Mark | Meaning |')
  md.push('|---|---|')
  md.push(
    '| ✓ | caught: at least one baseline-green test file in the group went red under the toggle, and re-greened with it off |',
  )
  md.push('| ✗ | missed: the group ran and stayed green. Empirical blindness, not an assumption |')
  md.push('| n/a | no code path (different runtime) |')
  md.push('| n/r | not run yet |')
  if (artifact.cells.some((c) => c.status === 'skipped-cost')) {
    md.push('| $ | declared skipped-cost (key-gated) |')
  }
  if (artifact.cells.some((c) => c.status === 'unstable')) {
    md.push('| ~ | unstable |')
  }
  md.push('')
  md.push(
    'Abbreviated columns: pact-oas = pact-oas-crosscheck, rev-conf = reverse-conformance, py-conf = py-conformance.',
  )
  md.push('')
  const reds = artifact.baseline?.standing_reds.length ?? 0
  md.push(
    `**Totals: ${counts.caught} caught, ${counts.missed} missed, ${counts.caught + counts.missed} cells measured** (${ghostCount()} grid positions not applicable or not yet run). Baseline: \`${artifact.baseline?.commit.slice(0, 12) ?? 'none'}\` (${reds} standing red${reds === 1 ? '' : 's'}, fast-check seed ${artifact.baseline?.fastcheck_seed ?? '?'}). Last render: ${artifact.generated_at}. A frozen, hash-stamped snapshot of every cell is committed at [docs/evidence/detection-matrix.snapshot.json](evidence/detection-matrix.snapshot.json), so the grid is verifiable without cloning the gitignored artifact.`,
  )
  md.push('')

  // The heat-grid + the three curated rows used to live in the README; they now live here, the
  // single gated home, so the whole-doc byte gate (pnpm matrix:verify) protects their derived
  // counts. Asset/snapshot links are doc-relative (this file is docs/detection-matrix.md).
  md.push(renderDocHeatGrid())
  md.push('')
  md.push(renderDocTeaser())
  md.push('')

  md.push('## In-proc tier (Tier A)')
  md.push('')
  md.push(`| toggle | ${[...TS_COLUMNS, ...PY_COLUMNS].map(label).join(' | ')} |`)
  md.push(`|---|${[...TS_COLUMNS, ...PY_COLUMNS].map(() => '---').join('|')}|`)
  for (const t of TOGGLES.filter((t) => t.tiers.includes('in-proc'))) {
    const isPy = t.component === 'moderator'
    md.push(`| \`${t.id}\` | ${row(t.id, isPy, [...TS_COLUMNS, ...PY_COLUMNS], 'in-proc')} |`)
  }
  md.push('')

  if (artifact.cells.some((c) => c.tier === 'cluster')) {
    md.push('## Cluster tier (Tier B)')
    md.push('')
    md.push(`| toggle | ${LIVE_COLUMNS.map(label).join(' | ')} |`)
    md.push(`|---|${LIVE_COLUMNS.map(() => '---').join('|')}|`)
    for (const t of TOGGLES.filter((t) => t.tiers.includes('cluster'))) {
      md.push(`| \`${t.id}\` | ${row(t.id, false, LIVE_COLUMNS, 'cluster')} |`)
    }
    md.push('')
  }

  if (artifact.cells.some((c) => c.tier === 'llm')) {
    md.push('## LLM tier (Tier C, cost-recorded)')
    md.push('')
    md.push(`| toggle | ${[...LLM_COLUMNS, 'metamorphic'].map(label).join(' | ')} |`)
    md.push(`|---|${[...LLM_COLUMNS, 'metamorphic'].map(() => '---').join('|')}|`)
    for (const t of TOGGLES.filter((t) => t.tiers.includes('llm'))) {
      md.push(`| \`${t.id}\` | ${row(t.id, false, [...LLM_COLUMNS, 'metamorphic'], 'llm')} |`)
    }
    md.push('')
  }

  md.push('## Per-toggle detail')
  md.push('')
  for (const t of TOGGLES) {
    const caught = artifact.cells.filter((c) => c.toggle === t.id && c.status === 'caught')
    const files = [...new Set(caught.flatMap((c) => c.evidence.newly_failing))].sort()
    md.push(`### \`${t.id}\`: \`${t.env.name}=${t.env.value}\``)
    md.push('')
    md.push(`- component: ${t.component}; read at ${t.readSite.file} (${t.readSite.timing})`)
    md.push(`- designated catcher: ${t.designatedCatcher ?? 'none (purely empirical)'}`)
    if (t.claimId) md.push(`- permanent claim: \`${t.claimId}\` (pnpm prove ${t.claimId} --break)`)
    if (caught.length > 0) {
      md.push(
        `- **caught by ${caught.length} group(s)** (${caught.map((c) => `${c.technique}@${c.tier}`).join(', ')}); detection breadth ${caught.length}, blast radius ${files.length} file(s):`,
      )
      for (const f of files) md.push(`  - \`${f}\``)
    } else if (artifact.cells.some((c) => c.toggle === t.id)) {
      md.push('- **MISSED by every group that ran**: see notes')
    } else {
      md.push('- not run yet')
    }
    if (t.selfToggling.length > 0) {
      md.push(
        `- self-toggling files (excluded from naive counting): ${t.selfToggling.map((f) => `\`${f}\``).join(', ')}`,
      )
    }
    if (t.notes) md.push(`- notes: ${t.notes}`)
    md.push('')
  }
  return `${md.join('\n')}\n`
}

// ---- README projections (the 2026-06-11 front-door brief) ----

function tierGrid(
  tier: MatrixCell['tier'],
  columns: string[],
  toggles: typeof TOGGLES,
): SvgTier['grid'] {
  return toggles.map((t) =>
    columns.map((col) => {
      const isPy = t.component === 'moderator'
      const crossRuntime =
        (isPy && tier === 'in-proc' && TS_COLUMNS.includes(col)) ||
        (!isPy && tier === 'in-proc' && PY_COLUMNS.includes(col))
      if (crossRuntime) return { status: 'other' as const }
      const cell = cellFor(t.id, col, tier)
      if (!cell) return { status: 'other' as const }
      if (cell.status === 'caught') return { status: 'caught' as const }
      if (cell.status === 'missed') return { status: 'missed' as const }
      return { status: 'other' as const }
    }),
  )
}

function buildTiers(): SvgTier[] {
  const tiers: SvgTier[] = [
    {
      label: 'Tier A · in-proc',
      grid: tierGrid(
        'in-proc',
        [...TS_COLUMNS, ...PY_COLUMNS],
        TOGGLES.filter((t) => t.tiers.includes('in-proc')),
      ),
    },
  ]
  if (artifact.cells.some((c) => c.tier === 'cluster')) {
    tiers.push({
      label: 'Tier B · live cluster',
      grid: tierGrid(
        'cluster',
        LIVE_COLUMNS,
        TOGGLES.filter((t) => t.tiers.includes('cluster')),
      ),
    })
  }
  if (artifact.cells.some((c) => c.tier === 'llm')) {
    tiers.push({
      label: 'Tier C · real model',
      grid: tierGrid(
        'llm',
        [...LLM_COLUMNS, 'metamorphic'],
        TOGGLES.filter((t) => t.tiers.includes('llm')),
      ),
    })
  }
  return tiers
}

const counts = {
  caught: artifact.cells.filter((c) => c.status === 'caught').length,
  missed: artifact.cells.filter((c) => c.status === 'missed').length,
}

const gridCells = () => buildTiers().flatMap((t) => t.grid.flat()).length
const ghostCount = () => gridCells() - counts.caught - counts.missed

// ---- in-doc projections: the heat grid + curated rows, folded in from the old README blocks ----
// Asset/snapshot links are doc-relative (this renders into docs/detection-matrix.md).

function renderDocHeatGrid(): string {
  return `## The grid at a glance

> **${counts.caught} catches. ${counts.missed} recorded misses. The misses are the point.**
> Every deliberate bug in this repo is armed, one at a time, against every testing technique. A filled cell is a catch. A hollow cell is a technique that ran and stayed green: measured blindness, recorded instead of hidden. The ${ghostCount()} faint cells are not applicable or not yet run.

<picture>
<source media="(prefers-color-scheme: dark)" srcset="assets/detection-matrix-dark.svg">
<img alt="The detection matrix as a heat grid: ${counts.caught} filled cells (catches) and ${counts.missed} hollow cells (recorded misses) across three tiers" src="assets/detection-matrix-light.svg">
</picture>`
}

// Three curated rows: the matrix stories that say the most in one line each. Chosen by hand
// (best narrative, not best score) and rendered with live per-row counts so they cannot drift.
const TEASER_ROWS: [string, string][] = [
  [
    'feed-reversed',
    'A reversed feed passed the entire in-proc battery. The hole was closed the same day; the row re-ran ✗ to ✓.',
  ],
  [
    'vote-slow',
    'Invisible to every functional technique, by design: suites get slower, not redder. Only the k6 SLO threshold sees it.',
  ],
  [
    'disable-circuit-breaker',
    'Missed in-proc, structurally. Caught live by paced fuzz traffic through an accidentally sick upstream.',
  ],
]

function renderDocTeaser(): string {
  const rows = TEASER_ROWS.map(([id, story]) => {
    const measured = artifact.cells.filter((c) => c.toggle === id)
    const caught = measured.filter((c) => c.status === 'caught').length
    return `| \`${id}\` | ${caught} of ${measured.length} | ${story} |`
  }).join('\n')
  return `### Three rows worth calling out

| Deliberate bug | Caught by | What happened |
|---|---|---|
${rows}`
}

const snapshotPath = resolve(ROOT, 'docs/evidence/detection-matrix.snapshot.json')

// The committed, hash-stamped evidence snapshot: every measured cell, in the tree, so a reader
// who will not clone-and-run can still verify the grid instead of trusting the prose. The raw
// artifact stays gitignored (it carries volatile per-run detail); this is its frozen projection,
// and the sha256 binds the two: anyone with the artifact can recompute the hash.
function renderSnapshot(): string {
  const cells = [...artifact.cells]
    .map((c) => ({ toggle: c.toggle, technique: c.technique, tier: c.tier, status: c.status }))
    .sort(
      (a, b) =>
        a.toggle.localeCompare(b.toggle) ||
        a.tier.localeCompare(b.tier) ||
        a.technique.localeCompare(b.technique),
    )
  const snapshot = {
    generated_at: artifact.generated_at,
    baseline: {
      commit: artifact.baseline?.commit ?? null,
      fastcheck_seed: artifact.baseline?.fastcheck_seed ?? null,
      standing_reds: artifact.baseline?.standing_reds.length ?? 0,
    },
    counts: { ...counts, measured: counts.caught + counts.missed },
    artifact_sha256: createHash('sha256').update(readFileSync(artifactPath)).digest('hex'),
    cells,
  }
  return `${JSON.stringify(snapshot, null, 2)}\n`
}

function main(): void {
  const doc = renderDoc()
  const tiers = buildTiers()
  const svgLight = renderMatrixSvg(tiers, 'light')
  const svgDark = renderMatrixSvg(tiers, 'dark')

  if (process.argv.includes('--check')) {
    const problems: string[] = []
    const committed = existsSync(docPath) ? readFileSync(docPath, 'utf8') : ''
    if (committed !== doc) problems.push('docs/detection-matrix.md is stale')
    if (!existsSync(svgLightPath) || readFileSync(svgLightPath, 'utf8') !== svgLight) {
      problems.push('docs/assets/detection-matrix-light.svg is stale')
    }
    if (!existsSync(svgDarkPath) || readFileSync(svgDarkPath, 'utf8') !== svgDark) {
      problems.push('docs/assets/detection-matrix-dark.svg is stale')
    }
    if (!existsSync(snapshotPath) || readFileSync(snapshotPath, 'utf8') !== renderSnapshot()) {
      problems.push('docs/evidence/detection-matrix.snapshot.json is stale')
    }
    if (problems.length > 0) {
      for (const p of problems) process.stderr.write(`✗ ${p} — run pnpm matrix:render\n`)
      process.exit(1)
    }
    process.stdout.write('✓ matrix doc, SVGs, and evidence snapshot match a fresh render\n')
    process.exit(0)
  }

  mkdirSync(assetsDir, { recursive: true })
  mkdirSync(resolve(ROOT, 'docs/evidence'), { recursive: true })
  writeFileSync(docPath, doc)
  writeFileSync(svgLightPath, svgLight)
  writeFileSync(svgDarkPath, svgDark)
  writeFileSync(snapshotPath, renderSnapshot())
  process.stdout.write(
    `wrote docs/detection-matrix.md (${artifact.cells.length} cells) + docs/assets/detection-matrix-{light,dark}.svg + docs/evidence/detection-matrix.snapshot.json\n`,
  )
}

main()
