import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { BOUNDARY_REGISTRY } from './lib/manifests/boundary-registry'
import { CLAIMS } from './lib/manifests/claims'

/**
 * Render the falsifiable-claim manifest into its reader projections: docs/claims.md (the dare —
 * GitHub-renderable) and the stable block in ARCHITECTURE.md §4. Both are DERIVED from the one
 * manifest, so nothing is hand-typed. Neither projection commits a live PASS/STALE verdict: that
 * verdict is per-run (it reads stale the moment the snapshot moves), so it lives in
 * `pnpm claims:verify` / a CI run's summary.json, never in a committed file. The projections carry
 * only stable facts (claim, boundary, toggle, falsify command), so they stay byte-comparable and
 * claims:verify drift-gates them.
 *
 *   pnpm claims:render            write docs/claims.md
 *   pnpm claims:render --readme   print the stable block to stdout (for injection into ARCHITECTURE.md + the gate)
 */

const ROOT = process.cwd()

// The GitHub-renderable page: the DARE, not a verdict board. Stable facts only (no per-run
// PASS/STALE column) so the committed file never reads stale — the 2026-06 fix for "claims.md shows
// N stale on the front door at an old commit stamp". The live verdict comes from `pnpm claims:verify`.
export function renderClaimsMarkdown(): string {
  const boundaries = new Set(CLAIMS.map((c) => c.registryRow)).size
  const rows = CLAIMS.map(
    (claim) =>
      `| ${claim.claim} | \`${claim.registryRow}\` | \`${claim.toggle}\` | \`pnpm prove ${claim.id} --break\` |`,
  ).join('\n')
  return `# Guarantees you can break: the claims list

> Generated by \`pnpm claims:render\`; do not edit by hand. ${CLAIMS.length} guarantees ("falsifiable claims") across ${boundaries} of the ${BOUNDARY_REGISTRY.length} parts of the system.

**A "falsifiable claim" is a promise that comes with its own off switch.** Each row is something the
system guarantees, plus the exact bug that would break it and one command to watch a real test catch
that bug. Don't trust the green check, flip the switch and see the test fail. The live pass or fail
verdict is not committed here (it would read stale the moment the code moves); get it from
\`pnpm claims:verify\` or a CI run.

| Claim | Boundary | Breaks when | Falsify |
|---|---|---|---|
${rows}

A claim that cannot go red when its toggle is set fails \`pnpm claims:verify\` outright: that is the
gate, not this page.
`
}

// Stable block (lives in ARCHITECTURE.md §4), manifest projection only (NO live numbers), so it is
// byte-comparable and drift-gated by claims:verify. The README_* names are kept as identifiers for
// compatibility; the marker string is `claims:*`.
export const README_START =
  '<!-- claims:start (generated by `pnpm claims:render --readme`; do not edit) -->'
export const README_END = '<!-- claims:end -->'
export function renderReadmeBlock(): string {
  const rows = CLAIMS.map((c) => `| ${c.claim} | \`${c.registryRow}\` | \`${c.id}\` |`).join('\n')
  return `${README_START}
## Falsifiable claims

> Don't trust the green check. Flip the switch. Every claim comes with the bug that breaks it and the test that catches that bug — run one command and a real test turns red. The live PASS/STALE verdict comes from the test run (\`pnpm claims:verify\`), never hand-typed. Full list, with the toggle and falsify command per claim: [docs/claims.md](docs/claims.md); the matrix: \`pnpm prove\`.

Falsify any row: \`pnpm prove <id> --break\`. The toggle each claim breaks under is in [docs/claims.md](docs/claims.md).

| Claim | Boundary | Id |
|---|---|---|
${rows}
${README_END}`
}

function main(): void {
  if (process.argv.includes('--readme')) {
    process.stdout.write(`${renderReadmeBlock()}\n`)
    return
  }
  writeFileSync(resolve(ROOT, 'docs/claims.md'), renderClaimsMarkdown())
  process.stdout.write(`wrote docs/claims.md (${CLAIMS.length} claims)\n`)
}

// Run only when invoked directly; importing for renderReadmeBlock (claims-verify) must be side-effect-free.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main()
}
