import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

/**
 * Render the QARoom "LLM run cost" projection: a drift-gated block (lives in docs/03-testing-strategy.md)
 * showing what one on-demand eval run is estimated to cost, per lane, at the vendored prices in
 * services/moderator-agent/evals/cost-model.json. Mirrors render-stats.ts: side-effect-free renderer +
 * markers, byte-gated by claims-verify.ts. STABLE by construction — it carries the estimate + dollars
 * but NOT the per-run timestamp (that volatile freshness signal lives in the gitignored
 * test-results/cost-ledger.json the Python `cost:ledger` writes after a run). The numbers mirror the
 * Python guard's estimate (same cost-model.json, same heuristics) so the doc and the CI ceiling
 * never disagree.
 *
 *   pnpm cost:render            print the block
 *   pnpm cost:render --readme   same (for injection into docs/03 + the gate)
 */

const ROOT = process.cwd()
const MOD = resolve(ROOT, 'services/moderator-agent')

interface CostModel {
  prices: Record<string, { input_per_1m: number; output_per_1m: number }>
  estimate: Record<string, number>
}

function read<T>(path: string): T {
  return JSON.parse(readFileSync(path, 'utf8')) as T
}

function usd(model: string, input: number, output: number, prices: CostModel['prices']): number {
  const rate = prices[model]
  if (!rate) return 0
  return (input * rate.input_per_1m + output * rate.output_per_1m) / 1_000_000
}

const MODEL = 'openai:gpt-5-nano-2025-08-07'

interface Lane {
  name: string
  tokens: number
  usd: number
}

/** Mirror of cost.estimate_lanes (Python) — same cost-model.json, same arithmetic. */
function estimateLanes(): Lane[] {
  const cm = read<CostModel>(resolve(MOD, 'evals/cost-model.json'))
  const e = cm.estimate
  const prices = cm.prices
  const prompt = read<{ content: string }[]>(resolve(MOD, 'evals/moderation.prompt.json'))
  const systemChars = prompt.reduce((n, m) => n + m.content.length, 0)
  const gold = read<{ cases: { post?: string; status?: string }[] }>(
    resolve(MOD, 'evals/golden/gold.json'),
  )
  const posts = gold.cases.filter((c) => c.status === 'gold').map((c) => c.post ?? '')

  const goldInput = posts.reduce((n, p) => n + Math.floor((systemChars + p.length) / 4), 0)
  const goldOutput = posts.length * e.gold_completion_tokens_per_case
  const goldTokens = (goldInput + goldOutput) * e.judged_calls_per_case
  const goldUsd = usd(
    MODEL,
    goldInput * e.judged_calls_per_case,
    goldOutput * e.judged_calls_per_case,
    prices,
  )

  const dtTokens = e.deepteam_attacks * e.deepteam_calls_per_attack * e.deepteam_tokens_per_call
  const prTokens =
    e.pyrit_objectives * e.pyrit_turns * e.pyrit_calls_per_turn * e.pyrit_tokens_per_call

  return [
    { name: 'gold-deepeval', tokens: goldTokens, usd: goldUsd },
    {
      name: 'deepteam-owasp',
      tokens: dtTokens,
      usd: usd(MODEL, Math.floor(dtTokens / 2), dtTokens - Math.floor(dtTokens / 2), prices),
    },
    {
      name: 'pyrit-nightly',
      tokens: prTokens,
      usd: usd(MODEL, Math.floor(prTokens / 2), prTokens - Math.floor(prTokens / 2), prices),
    },
  ]
}

export const COST_START =
  '<!-- cost:start (generated by `pnpm cost:render --readme`; do not edit) -->'
export const COST_END = '<!-- cost:end -->'

export function renderCostBlock(): string {
  const lanes = estimateLanes()
  const totalTokens = lanes.reduce((n, l) => n + l.tokens, 0)
  const totalUsd = lanes.reduce((n, l) => n + l.usd, 0)
  const rows = lanes
    .map((l) => `| \`${l.name}\` | ${l.tokens.toLocaleString('en-US')} | $${l.usd.toFixed(4)} |`)
    .join('\n')
  return `${COST_START}
**LLM run cost (estimate).** One on-demand eval run, \`${MODEL}\`, at vendored prices:

| Lane | Est. tokens | Est. cost |
|---|--:|--:|
${rows}
| **total** | **${totalTokens.toLocaleString('en-US')}** | **$${totalUsd.toFixed(4)}** |

<sub>Pre-flight estimate, not a measured bill: the eval harnesses (DeepEval/DeepTeam/PyRIT) report no token usage, so \`pnpm --filter @qaroom/moderator-agent eval:cost\` bounds the run against \`MODERATOR_EVAL_BUDGET_TOKENS\` and \`cost:ledger\` stamps the actual per-run record (with date) into \`test-results/cost-ledger.json\`. Prices are vendored in \`evals/cost-model.json\` — the \`gpt-5.5\` rate is a placeholder (no public price exists for a pinned future-dated model). Numbers derive from that file; \`pnpm claims:verify\` fails if this block drifts.</sub>
${COST_END}`
}

function main(): void {
  process.stdout.write(`${renderCostBlock()}\n`)
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main()
}
