import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { TOGGLES } from '@qaroom/contracts/detection-matrix'
import { DetectionMatrixArtifact, type MatrixCell } from '@qaroom/contracts/detection-matrix-schema'

/**
 * Render docs/detection-matrix.md from test-results/detection-matrix.json — the committed,
 * human-readable projection of the matrix experiment. Derived-only (render-claims discipline):
 * every cell comes from the artifact; nothing is hand-typed.
 *
 *   pnpm matrix:render           # write docs/detection-matrix.md
 *   pnpm matrix:render --check   # drift gate: committed file must equal a fresh render
 *
 * Freshness is deliberately NOT CI-gated — cluster and llm tiers cannot run per-PR, and
 * pretending they could would be theater. Staleness stays visible per-cell (commit + date).
 */
const ROOT = process.cwd()
const artifactPath = resolve(ROOT, 'test-results/detection-matrix.json')
const docPath = resolve(ROOT, 'docs/detection-matrix.md')

if (!existsSync(artifactPath)) {
  process.stderr.write('no test-results/detection-matrix.json — run pnpm matrix first\n')
  process.exit(2)
}
const artifact = DetectionMatrixArtifact.parse(JSON.parse(readFileSync(artifactPath, 'utf8')))

const TS_COLUMNS = [
  'unit',
  'integration',
  'property',
  'mbt',
  'pact',
  'pact-oas-crosscheck',
  'reverse-conformance',
]
const PY_COLUMNS = ['py-unit', 'py-conformance', 'metamorphic']
const LIVE_COLUMNS = ['smoke', 'k6', 'schemathesis', 'tracetest', 'tenant-spans', 'chaos']
const LLM_COLUMNS = ['deepeval', 'redteam']

const MARK: Record<MatrixCell['status'], string> = {
  caught: '✓',
  missed: '✗',
  na: '—',
  'skipped-cost': '$',
  unstable: '~',
}

const cellFor = (toggleId: string, technique: string, tier: MatrixCell['tier']) =>
  artifact.cells.find((c) => c.toggle === toggleId && c.technique === technique && c.tier === tier)

function row(toggleId: string, isPy: boolean, columns: string[], tier: MatrixCell['tier']): string {
  return columns
    .map((col) => {
      const crossRuntime =
        (isPy && tier === 'in-proc' && TS_COLUMNS.includes(col)) ||
        (!isPy && tier === 'in-proc' && PY_COLUMNS.includes(col))
      if (crossRuntime) return '—'
      const cell = cellFor(toggleId, col, tier)
      return cell ? MARK[cell.status] : '·'
    })
    .join(' | ')
}

const md: string[] = []
md.push('# The detection matrix')
md.push('')
md.push(
  '> Generated by `pnpm matrix:render` from `test-results/detection-matrix.json` — do not edit by hand (`pnpm matrix:verify` gates drift).',
)
md.push('')
md.push(
  `Every deliberate-bug toggle in the repo, armed one at a time, against the whole in-proc battery. A ✓ means at least one baseline-green test file in that technique group went red under the toggle (and passed a toggle-off re-run); a ✗ means the group ran and stayed green — empirical blindness, not an assumption. \`—\` = no code path (different runtime), \`$\` = declared skipped-cost (key-gated), \`~\` = unstable, \`·\` = not run yet.`,
)
md.push('')
md.push(
  `Baseline: \`${artifact.baseline?.commit.slice(0, 12) ?? 'none'}\` (${artifact.baseline?.standing_reds.length ?? 0} standing reds, fast-check seed ${artifact.baseline?.fastcheck_seed ?? '?'}). Last render: ${artifact.generated_at}.`,
)
md.push('')

md.push('## In-proc tier (Tier A)')
md.push('')
md.push(`| toggle | ${[...TS_COLUMNS, ...PY_COLUMNS].join(' | ')} |`)
md.push(`|---|${[...TS_COLUMNS, ...PY_COLUMNS].map(() => '---').join('|')}|`)
for (const t of TOGGLES.filter((t) => t.tiers.includes('in-proc'))) {
  const isPy = t.component === 'moderator'
  md.push(`| \`${t.id}\` | ${row(t.id, isPy, [...TS_COLUMNS, ...PY_COLUMNS], 'in-proc')} |`)
}
md.push('')

const clusterCells = artifact.cells.filter((c) => c.tier === 'cluster')
if (clusterCells.length > 0) {
  md.push('## Cluster tier (Tier B)')
  md.push('')
  md.push(`| toggle | ${LIVE_COLUMNS.join(' | ')} |`)
  md.push(`|---|${LIVE_COLUMNS.map(() => '---').join('|')}|`)
  for (const t of TOGGLES.filter((t) => t.tiers.includes('cluster'))) {
    md.push(`| \`${t.id}\` | ${row(t.id, false, LIVE_COLUMNS, 'cluster')} |`)
  }
  md.push('')
}

const llmCells = artifact.cells.filter((c) => c.tier === 'llm')
if (llmCells.length > 0) {
  md.push('## LLM tier (Tier C, cost-recorded)')
  md.push('')
  md.push(`| toggle | ${[...LLM_COLUMNS, 'metamorphic'].join(' | ')} |`)
  md.push(`|---|${[...LLM_COLUMNS, 'metamorphic'].map(() => '---').join('|')}|`)
  for (const t of TOGGLES.filter((t) => t.tiers.includes('llm'))) {
    md.push(`| \`${t.id}\` | ${row(t.id, false, [...LLM_COLUMNS, 'metamorphic'], 'llm')} |`)
  }
  md.push('')
}

md.push('## Per-toggle detail')
md.push('')
for (const t of TOGGLES) {
  const caught = artifact.cells.filter((c) => c.toggle === t.id && c.status === 'caught')
  const files = [...new Set(caught.flatMap((c) => c.evidence.newly_failing))].sort()
  md.push(`### \`${t.id}\` — \`${t.env.name}=${t.env.value}\``)
  md.push('')
  md.push(`- component: ${t.component}; read at ${t.readSite.file} (${t.readSite.timing})`)
  md.push(`- designated catcher: ${t.designatedCatcher ?? 'none (purely empirical)'}`)
  if (t.claimId) md.push(`- permanent claim: \`${t.claimId}\` (pnpm prove ${t.claimId} --break)`)
  if (caught.length > 0) {
    md.push(
      `- **caught by ${caught.length} group(s)** (${caught.map((c) => `${c.technique}@${c.tier}`).join(', ')}); detection breadth ${caught.length}, blast radius ${files.length} file(s):`,
    )
    for (const f of files) md.push(`  - \`${f}\``)
  } else if (artifact.cells.some((c) => c.toggle === t.id)) {
    md.push('- **MISSED by every group that ran** — see notes')
  } else {
    md.push('- not run yet')
  }
  if (t.selfToggling.length > 0) {
    md.push(
      `- self-toggling files (excluded from naive counting): ${t.selfToggling.map((f) => `\`${f}\``).join(', ')}`,
    )
  }
  if (t.notes) md.push(`- notes: ${t.notes}`)
  md.push('')
}

const rendered = `${md.join('\n')}\n`

if (process.argv.includes('--check')) {
  const committed = existsSync(docPath) ? readFileSync(docPath, 'utf8') : ''
  if (committed !== rendered) {
    process.stderr.write(
      'docs/detection-matrix.md is stale vs test-results/detection-matrix.json — run pnpm matrix:render\n',
    )
    process.exit(1)
  }
  process.stdout.write('✓ docs/detection-matrix.md matches a fresh render\n')
  process.exit(0)
}

writeFileSync(docPath, rendered)
process.stdout.write(`wrote docs/detection-matrix.md (${artifact.cells.length} cells)\n`)
